<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3RndWKv\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3RndWKv/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/Container3RndWKv.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\Container3RndWKv\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \Container3RndWKv\srcApp_KernelTestDebugContainer([
    'container.build_hash' => '3RndWKv',
    'container.build_id' => '954e9d90',
    'container.build_time' => 1564996660,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3RndWKv');
