<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LCzegZE' shared service.

return $this->privates['.service_locator.LCzegZE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AuthentificationController::index' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::argent' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::index' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController::user' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\AuthentificationController:index' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:adduser' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:argent' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:index' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
    'App\\Controller\\ServiceController:user' => ['privates', '.service_locator.JBoVXlr', 'get_ServiceLocator_JBoVXlrService.php', true],
], [
    'App\\Controller\\AuthentificationController::index' => '?',
    'App\\Controller\\ServiceController::adduser' => '?',
    'App\\Controller\\ServiceController::argent' => '?',
    'App\\Controller\\ServiceController::index' => '?',
    'App\\Controller\\ServiceController::user' => '?',
    'App\\Controller\\AuthentificationController:index' => '?',
    'App\\Controller\\ServiceController:adduser' => '?',
    'App\\Controller\\ServiceController:argent' => '?',
    'App\\Controller\\ServiceController:index' => '?',
    'App\\Controller\\ServiceController:user' => '?',
]);
