<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVqrbxkH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVqrbxkH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVqrbxkH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVqrbxkH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerVqrbxkH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'VqrbxkH',
    'container.build_id' => '1a81f595',
    'container.build_time' => 1565007864,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVqrbxkH');
