<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGoMT5Te\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGoMT5Te/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGoMT5Te.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGoMT5Te\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGoMT5Te\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GoMT5Te',
    'container.build_id' => '7e9a233e',
    'container.build_time' => 1565259870,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGoMT5Te');
