<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIrxQADO\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIrxQADO/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIrxQADO.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIrxQADO\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIrxQADO\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IrxQADO',
    'container.build_id' => '751bdb15',
    'container.build_time' => 1565266385,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIrxQADO');
